web:
  restart: always
  build: ./
  expose:
    - "5000"
  links:
    - postgres:db
  volumes:
    - .:/usr/src/python/app
    - ../resource-alchemy/:/resource-alchemy/
  env_file: ./containers/.env
  command: uwsgi --ini uwsgi.ini

nginx:
  restart: always
  build: ./containers/nginx/
  ports:
    - "443:443"
  volumes:
    - ./containers/nginx/sites-enabled/:/etc/nginx/sites-enabled/
    - ./certificates/:/etc/ssl/
    - ../color-schemer-frontend:/www/static/color-schemer-frontend
  links:
    - web:web

data:
  restart: 'no'
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  env_file: ./containers/.env
  command: ls

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
  env_file: ./containers/.env
