version: '2'

services:
  web:
    restart: always
    build: .
    expose:
      - "3030"
    links:
      - postgres:db
    volumes:
      - .:/usr/src/app
    env_file: ./containers/.env
    depends_on:
      - postgres
    command: npm start

  nginx:
    restart: always
    build: ./containers/nginx/
    ports:
      - "80:80"
    volumes:
      - ./containers/nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - .:/www/static/color-schemer-frontend
    links:
      - web:web

  data:
    restart: 'no'
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    env_file: ./containers/.env
    command: ls

  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
    env_file: ./containers/.env
